spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bayzdelivery
    username: db_user
    password: 123qwe
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
      ddl-auto: none