-- Table: public.delivery

-- DROP TABLE IF EXISTS public.delivery;

CREATE TABLE IF NOT EXISTS public.delivery
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    commission real,
    distance integer,
    end_time timestamp without time zone,
    price real,
    start_time timestamp without time zone NOT NULL,
    customer_id bigint,
    delivery_man_id bigint,
    CONSTRAINT delivery_pkey PRIMARY KEY (id),
    CONSTRAINT fk2g8ks13qbgp1prfin9uaiyvn2 FOREIGN KEY (delivery_man_id)
        REFERENCES public.person (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fklr38vvfk0spps9vdwja87kkkq FOREIGN KEY (customer_id)
        REFERENCES public.person (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.delivery
    OWNER to db_user;