-- Table: public.security_role

-- DROP TABLE IF EXISTS public.security_role;

CREATE TABLE public.security_role (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  description character varying(255) COLLATE pg_catalog."default" NOT NULL,
  role_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
  CONSTRAINT security_role_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.security_role
    OWNER to db_user;

-- Table: public.person_role

-- DROP TABLE IF EXISTS public.person_role;

CREATE TABLE person_role (
  person_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  CONSTRAINT FK_SECURITY_PERSON_ID FOREIGN KEY (person_id)
      REFERENCES public.person (id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE NO ACTION,
  CONSTRAINT FK_SECURITY_ROLE_ID FOREIGN KEY (role_id)
      REFERENCES public.security_role (id) MATCH SIMPLE
      ON UPDATE NO ACTION
      ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.person_role
    OWNER to db_user;
